// frontend/src/views/Settings.vue
<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Header -->
    <div class="mb-8">
      <h1 class="text-2xl font-bold text-gray-900 mb-2">Settings</h1>
      <p class="text-gray-600">Configure your AI summarization settings and preferences.</p>
    </div>

    <!-- Configuration Form -->
    <div class="card">
      <h2 class="text-xl font-semibold text-gray-900 mb-6">AI Configuration</h2>
      
      <form @submit.prevent="saveSettings" class="space-y-6">
        <!-- API Endpoint -->
        <div>
          <label class="label">API Endpoint</label>
          <input
            v-model="formData.apiEndpoint"
            type="url"
            class="input"
            placeholder="https://api.example.com/v1"
            required
          />
          <p class="text-sm text-gray-500 mt-1">
            The OpenAI-compatible API endpoint for summarization
          </p>
        </div>

        <!-- API Key -->
        <div>
          <label class="label">API Key</label>
          <input
            v-model="formData.apiKey"
            type="password"
            class="input"
            placeholder="Your API key"
            required
          />
          <p class="text-sm text-gray-500 mt-1">
            Your API key for authentication
          </p>
        </div>

        <!-- Model Name -->
        <div>
          <label class="label">Model Name</label>
          <input
            v-model="formData.modelName"
            type="text"
            class="input"
            placeholder="gpt-4"
            required
          />
          <p class="text-sm text-gray-500 mt-1">
            The model to use for summarization
          </p>
        </div>

        <!-- Default Ratio -->
        <div>
          <label class="label">Default Summary Ratio</label>
          <div class="flex items-center space-x-4">
            <input
              v-model.number="formData.defaultRatio"
              type="range"
              min="0.1"
              max="0.8"
              step="0.1"
              class="flex-1"
            />
            <span class="text-sm text-gray-600 w-12">{{ formData.defaultRatio }}</span>
          </div>
          <p class="text-sm text-gray-500 mt-1">
            Default compression ratio for AI summaries ({{ Math.round(formData.defaultRatio * 100) }}% of original length)
          </p>
        </div>

        <!-- Summarization Prompt -->
        <div>
          <label class="label">Summarization Prompt</label>
          <textarea
            v-model="formData.prompt"
            rows="6"
            class="textarea"
            placeholder="Enter your custom summarization prompt..."
            required
          />
          <p class="text-sm text-gray-500 mt-1">
            The system prompt used for AI summarization. This controls how the AI summarizes content.
          </p>
        </div>

        <!-- Action Buttons -->
        <div class="flex items-center justify-between pt-6 border-t border-gray-200">
          <button
            type="button"
            @click="resetToDefaults"
            class="btn btn-secondary"
          >
            Reset to Defaults
          </button>
          
          <div class="flex items-center space-x-3">
            <button
              type="button"
              @click="testConnection"
              :disabled="isTesting"
              class="btn btn-secondary"
            >
              <span v-if="isTesting">Testing...</span>
              <span v-else>Test Connection</span>
            </button>
            
            <button
              type="submit"
              :disabled="isSaving"
              class="btn btn-primary"
            >
              <span v-if="isSaving">Saving...</span>
              <span v-else>Save Settings</span>
            </button>
          </div>
        </div>
      </form>
    </div>

    <!-- Test Results -->
    <div v-if="testResult" class="mt-6">
      <div
        class="rounded-lg p-4"
        :class="{
          'bg-green-50 border border-green-200': testResult.success,
          'bg-red-50 border border-red-200': !testResult.success
        }"
      >
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <svg
              v-if="testResult.success"
              class="h-5 w-5 text-green-400"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                clip-rule="evenodd"
              />
            </svg>
            <svg
              v-else
              class="h-5 w-5 text-red-400"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                clip-rule="evenodd"
              />
            </svg>
          </div>
          <div class="ml-3">
            <p
              class="text-sm font-medium"
              :class="{
                'text-green-800': testResult.success,
                'text-red-800': !testResult.success
              }"
            >
              {{ testResult.message }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Current Configuration Display -->
    <div v-if="config" class="mt-8 card">
      <h3 class="text-lg font-medium text-gray-900 mb-4">Current Configuration</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
        <div>
          <span class="font-medium text-gray-700">Endpoint:</span>
          <span class="text-gray-600 ml-2">{{ config.apiEndpoint }}</span>
        </div>
        <div>
          <span class="font-medium text-gray-700">Model:</span>
          <span class="text-gray-600 ml-2">{{ config.modelName }}</span>
        </div>
        <div>
          <span class="font-medium text-gray-700">Default Ratio:</span>
          <span class="text-gray-600 ml-2">{{ Math.round(config.defaultRatio * 100) }}%</span>
        </div>
        <div>
          <span class="font-medium text-gray-700">API Key:</span>
          <span class="text-gray-600 ml-2">{{ config.apiKey ? '••••••••' : 'Not set' }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { useAppStore } from '@/stores/app';
import { storeToRefs } from 'pinia';
import type { SummarizationConfig } from '@/types';

const store = useAppStore();
const { config } = storeToRefs(store);
const { loadConfig, updateConfig } = store;

const isSaving = ref(false);
const isTesting = ref(false);
const testResult = ref<{ success: boolean; message: string } | null>(null);

const formData = reactive<SummarizationConfig>({
  apiEndpoint: '',
  apiKey: '',
  modelName: '',
  prompt: '',
  defaultRatio: 0.3
});

const defaultConfig: SummarizationConfig = {
  apiEndpoint: 'https://17aa5245425e480e805ff5c79c44fa18.constructor.pro/a023f5c813e74089ab9c5b3fc3c63f80',
  apiKey: 'qBqkWcSdYGFohFDwNDmL7plk7chQwcwPSWFzi5V6AKFEkRniD9SbSqw2YqV3qyjA',
  modelName: 'gpt-4.1',
  prompt: 'You are a helpful assistant that creates concise, accurate summaries of text content. Maintain the key information and main ideas while reducing the length according to the specified ratio. Keep the summary coherent and well-structured.',
  defaultRatio: 0.3
};

onMounted(async () => {
  await loadConfig();
  if (config.value) {
    Object.assign(formData, config.value);
  }
});

const saveSettings = async () => {
  try {
    isSaving.value = true;
    testResult.value = null;
    
    await updateConfig(formData);
    
    testResult.value = {
      success: true,
      message: 'Settings saved successfully!'
    };
  } catch (error) {
    testResult.value = {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to save settings'
    };
  } finally {
    isSaving.value = false;
  }
};

const testConnection = async () => {
  try {
    isTesting.value = true;
    testResult.value = null;
    
    // Test with a simple summarization request
    const testContent = "This is a test message to verify the AI connection is working properly.";
    
    await store.summarizeContent(testContent, 0.5);
    
    testResult.value = {
      success: true,
      message: 'Connection test successful! AI endpoint is working correctly.'
    };
  } catch (error) {
    testResult.value = {
      success: false,
      message: error instanceof Error ? error.message : 'Connection test failed'
    };
  } finally {
    isTesting.value = false;
  }
};

const resetToDefaults = () => {
  Object.assign(formData, defaultConfig);
  testResult.value = null;
};
</script>

// frontend-2/src/pages/Settings.tsx

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ApiService } from '@/services/api';
import { Logo } from '@/components/ui/logo';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Save, Settings as SettingsIcon, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface ConfigResponse {
  apiEndpoint: string;
  apiKey: string;
  modelName: string;
  prompt: string;
  defaultRatio: number;
}

const Settings = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [config, setConfig] = useState<ConfigResponse>({
    apiEndpoint: 'https://api.openai.com/v1',
    apiKey: '',
    modelName: 'gpt-4o-mini',
    prompt: 'You are a helpful assistant that creates concise, accurate summaries of text content. Maintain the key information and main ideas while reducing the length according to the specified ratio. Keep the summary coherent and well-structured.',
    defaultRatio: 0.3,
  });
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    loadConfig();
  }, []);

  const loadConfig = async () => {
    try {
      setLoading(true);
      const configData = await ApiService.getConfig();
      setConfig(configData);
    } catch (error) {
      console.error('Failed to load config:', error);
      toast({
        title: "Error",
        description: "Failed to load configuration settings",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const saveConfig = async () => {
    try {
      setSaving(true);
      await ApiService.updateConfig(config);
      toast({
        title: "Settings Saved",
        description: "Configuration has been updated successfully",
      });
    } catch (error) {
      console.error('Failed to save config:', error);
      toast({
        title: "Save Failed",
        description: "Could not save configuration. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-50 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-amber-500 animate-spin mx-auto mb-4" />
          <p className="text-gray-600">Loading settings...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-gray-200/50 sticky top-0 z-50">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                onClick={() => navigate('/')}
                className="hover:bg-amber-100"
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Library
              </Button>
              <div className="hidden md:block">
                <Logo />
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              <SettingsIcon className="w-5 h-5 text-gray-600" />
              <h1 className="text-xl font-semibold text-gray-900">Settings</h1>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-6 py-8 max-w-2xl">
        <Card className="bg-white/80 backdrop-blur-sm border-0 shadow-xl">
          <CardHeader>
            <CardTitle className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
              AI Configuration
            </CardTitle>
            <p className="text-gray-600">
              Configure OpenAI settings for summarization
            </p>
          </CardHeader>
          
          <CardContent className="space-y-6">
            {/* OpenAI API Key */}
            <div className="space-y-2">
              <Label htmlFor="apiKey">OpenAI API Key</Label>
              <Input
                id="apiKey"
                type="password"
                placeholder="sk-..."
                value={config.apiKey || ''}
                onChange={(e) => setConfig(prev => ({ ...prev, apiKey: e.target.value }))}
              />
              <p className="text-sm text-gray-500">
                Your API key is stored securely and used only for summarization requests
              </p>
            </div>

            {/* API Endpoint */}
            <div className="space-y-2">
              <Label htmlFor="apiEndpoint">API Endpoint</Label>
              <Input
                id="apiEndpoint"
                type="text"
                placeholder="https://api.openai.com/v1"
                value={config.apiEndpoint || ''}
                onChange={(e) => setConfig(prev => ({ ...prev, apiEndpoint: e.target.value }))}
              />
              <p className="text-sm text-gray-500">
                OpenAI API endpoint URL
              </p>
            </div>

            {/* Model Selection */}
            <div className="space-y-2">
              <Label htmlFor="model">AI Model</Label>
              <Select value={config.modelName} onValueChange={(value) => setConfig(prev => ({ ...prev, modelName: value }))}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="gpt-4o-mini">GPT-4O Mini (Fast & Economical)</SelectItem>
                  <SelectItem value="gpt-4o">GPT-4O (Powerful)</SelectItem>
                  <SelectItem value="gpt-4">GPT-4 (Legacy)</SelectItem>
                  <SelectItem value="gpt-3.5-turbo">GPT-3.5 Turbo (Economic)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Default Ratio */}
            <div className="space-y-2">
              <Label htmlFor="defaultRatio">Default Summarization Ratio</Label>
              <Input
                id="defaultRatio"
                type="number"
                min="0.1"
                max="0.8"
                step="0.1"
                value={config.defaultRatio}
                onChange={(e) => setConfig(prev => ({ ...prev, defaultRatio: parseFloat(e.target.value) }))}
              />
              <p className="text-sm text-gray-500">
                Default compression ratio for summaries (0.1 = very short, 0.8 = detailed)
              </p>
            </div>

            {/* System Prompt */}
            <div className="space-y-2">
              <Label htmlFor="prompt">System Prompt</Label>
              <textarea
                id="prompt"
                className="flex min-h-[100px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                placeholder="Enter the system prompt for AI summarization..."
                value={config.prompt || ''}
                onChange={(e) => setConfig(prev => ({ ...prev, prompt: e.target.value }))}
              />
              <p className="text-sm text-gray-500">
                Instructions for the AI on how to generate summaries
              </p>
            </div>

            {/* Save Button */}
            <Button 
              onClick={saveConfig}
              disabled={saving}
              className="w-full bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600"
            >
              {saving ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Save className="w-4 h-4 mr-2" />
              )}
              Save Configuration
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Settings;
